/*
* This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class AppTest {
    @Test
    public void testGetLength() {
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        double expected = 20.5;
        double actual = boat.getLength();
        assertEquals(expected, actual);
    }

    @Test
    public void testSetLength() {
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        double newLength = 18.3;
        boat.setLength(newLength);
        double expected = 18.3;
        double actual = boat.getLength();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetName() {
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        String expected = "MyBoat";
        String actual = boat.getName();
        assertEquals(expected, actual);
    }

    @Test
    public void testSetName() {
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        String newName = "NewBoat";
        boat.setName(newName);
        String expected = "NewBoat";
        String actual = boat.getName();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetType() {
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        String expected = "SailBoat";
        String actual = boat.getType();
        assertEquals(expected, actual);
    }

    @Test
    public void testToString() {
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        String expected = "BOAT:MyBoat:sailboat:20:5";
        String actual = boat.toString();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetBoatByName() {
        Member member = new Member("John Doe", "johndoe@example.com", "abc123");
        Boat boat1 = new SailBoat("MyBoat1", 20.5, 5.2);
        Boat boat2 = new MotorBoat("MyBoat2", 18.3, 300);
        member.addBoat(boat1);
        member.addBoat(boat2);
        Boat foundBoat = member.getBoatByName("MyBoat1");
        assertEquals(boat1, foundBoat);
    }

    @Test
    public void testGetBoatByNameNotFound() {
        Member member = new Member("John Doe", "johndoe@example.com", "abc123");
        Boat boat = new SailBoat("MyBoat", 20.5, 5.2);
        member.addBoat(boat);
        Boat foundBoat = member.getBoatByName("UnknownBoat");
        assertNull(foundBoat);
    }

}